# Generated by Django 3.2.8 on 2021-11-11 16:10

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва категорії')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва товару')),
                ('slug', models.SlugField()),
                ('description', models.TextField(null=True, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Ціна')),
                ('image1', models.ImageField(blank=True, upload_to='', verbose_name='Зображення 1')),
                ('color1', models.CharField(blank=True, choices=[(None, 'NoColor'), ('#000000', 'Black'), ('#696969', 'Grey'), ('#0000FF', 'Blue'), ('#008000', 'Green'), ('#FF0000', 'Red'), ('#D2691E', 'Orange'), ('#DA70D6', 'Violet'), ('#87CEFA', 'Light Blue'), ('#FFFAFA', 'White'), ('#FFC0CB', 'Pink')], max_length=100, verbose_name='Колір зображення 1')),
                ('image2', models.ImageField(blank=True, upload_to='', verbose_name='Зображення 2')),
                ('color2', models.CharField(blank=True, choices=[(None, 'NoColor'), ('#000000', 'Black'), ('#696969', 'Grey'), ('#0000FF', 'Blue'), ('#008000', 'Green'), ('#FF0000', 'Red'), ('#D2691E', 'Orange'), ('#DA70D6', 'Violet'), ('#87CEFA', 'Light Blue'), ('#FFFAFA', 'White'), ('#FFC0CB', 'Pink')], max_length=100, verbose_name='Колір зображення 2')),
                ('image3', models.ImageField(blank=True, upload_to='', verbose_name='Зображення 3')),
                ('color3', models.CharField(blank=True, choices=[(None, 'NoColor'), ('#000000', 'Black'), ('#696969', 'Grey'), ('#0000FF', 'Blue'), ('#008000', 'Green'), ('#FF0000', 'Red'), ('#D2691E', 'Orange'), ('#DA70D6', 'Violet'), ('#87CEFA', 'Light Blue'), ('#FFFAFA', 'White'), ('#FFC0CB', 'Pink')], max_length=100, verbose_name='Колір зображення 3')),
                ('image4', models.ImageField(blank=True, upload_to='', verbose_name='Зображення 4')),
                ('color4', models.CharField(blank=True, choices=[(None, 'NoColor'), ('#000000', 'Black'), ('#696969', 'Grey'), ('#0000FF', 'Blue'), ('#008000', 'Green'), ('#FF0000', 'Red'), ('#D2691E', 'Orange'), ('#DA70D6', 'Violet'), ('#87CEFA', 'Light Blue'), ('#FFFAFA', 'White'), ('#FFC0CB', 'Pink')], max_length=100, verbose_name='Колір зображення 4')),
                ('image5', models.ImageField(blank=True, upload_to='', verbose_name='Зображення 5')),
                ('color5', models.CharField(blank=True, choices=[(None, 'NoColor'), ('#000000', 'Black'), ('#696969', 'Grey'), ('#0000FF', 'Blue'), ('#008000', 'Green'), ('#FF0000', 'Red'), ('#D2691E', 'Orange'), ('#DA70D6', 'Violet'), ('#87CEFA', 'Light Blue'), ('#FFFAFA', 'White'), ('#FFC0CB', 'Pink')], max_length=100, verbose_name='Колір зображення 5')),
                ('image6', models.ImageField(blank=True, upload_to='', verbose_name='Зображення 6')),
                ('color6', models.CharField(blank=True, choices=[(None, 'NoColor'), ('#000000', 'Black'), ('#696969', 'Grey'), ('#0000FF', 'Blue'), ('#008000', 'Green'), ('#FF0000', 'Red'), ('#D2691E', 'Orange'), ('#DA70D6', 'Violet'), ('#87CEFA', 'Light Blue'), ('#FFFAFA', 'White'), ('#FFC0CB', 'Pink')], max_length=100, verbose_name='Колір зображення 6')),
                ('display', models.CharField(max_length=255, verbose_name='Діагональ, розширення, тип, інші особливості')),
                ('battery', models.CharField(max_length=255, verbose_name='Об`єм акумулятора')),
                ('memory', models.CharField(max_length=255, verbose_name='Об`єм оперативної та вбудованої пам`яті')),
                ('main_cam_mp', models.CharField(max_length=255, verbose_name='Основна камера')),
                ('frontal_cam_mp', models.CharField(max_length=255, verbose_name='Фронтальна камера')),
                ('soc', models.CharField(max_length=255, verbose_name='Процесор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.categories', verbose_name='Категорія')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
