# Generated by Django 3.2.8 on 2021-11-02 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва категорії')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва товару')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(null=True, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Ціна')),
                ('image1', models.ImageField(blank=True, upload_to='', verbose_name='Зображення 1')),
                ('color1', models.CharField(blank=True, choices=[('#000000', 'Black'), ('#696969', 'Grey'), ('#0000FF', 'Blue'), ('#008000', 'Green'), ('#FF0000', 'Red'), ('#D2691E', 'Orange'), ('#DA70D6', 'Violet'), ('#87CEFA', 'Light Blue'), ('#FFFAFA', 'White'), ('#FFC0CB', 'Pink')], default=None, max_length=100, verbose_name='Колір зображення 1')),
                ('image2', models.ImageField(blank=True, upload_to='', verbose_name='Зображення 2')),
                ('color2', models.CharField(blank=True, choices=[('#000000', 'Black'), ('#696969', 'Grey'), ('#0000FF', 'Blue'), ('#008000', 'Green'), ('#FF0000', 'Red'), ('#D2691E', 'Orange'), ('#DA70D6', 'Violet'), ('#87CEFA', 'Light Blue'), ('#FFFAFA', 'White'), ('#FFC0CB', 'Pink')], default=None, max_length=100, verbose_name='Колір зображення 2')),
                ('image3', models.ImageField(blank=True, upload_to='', verbose_name='Зображення 3')),
                ('color3', models.CharField(blank=True, choices=[('#000000', 'Black'), ('#696969', 'Grey'), ('#0000FF', 'Blue'), ('#008000', 'Green'), ('#FF0000', 'Red'), ('#D2691E', 'Orange'), ('#DA70D6', 'Violet'), ('#87CEFA', 'Light Blue'), ('#FFFAFA', 'White'), ('#FFC0CB', 'Pink')], default=None, max_length=100, verbose_name='Колір зображення 3')),
                ('image4', models.ImageField(blank=True, upload_to='', verbose_name='Зображення 4')),
                ('color4', models.CharField(blank=True, choices=[('#000000', 'Black'), ('#696969', 'Grey'), ('#0000FF', 'Blue'), ('#008000', 'Green'), ('#FF0000', 'Red'), ('#D2691E', 'Orange'), ('#DA70D6', 'Violet'), ('#87CEFA', 'Light Blue'), ('#FFFAFA', 'White'), ('#FFC0CB', 'Pink')], default=None, max_length=100, verbose_name='Колір зображення 4')),
                ('image5', models.ImageField(blank=True, upload_to='', verbose_name='Зображення 5')),
                ('color5', models.CharField(blank=True, choices=[('#000000', 'Black'), ('#696969', 'Grey'), ('#0000FF', 'Blue'), ('#008000', 'Green'), ('#FF0000', 'Red'), ('#D2691E', 'Orange'), ('#DA70D6', 'Violet'), ('#87CEFA', 'Light Blue'), ('#FFFAFA', 'White'), ('#FFC0CB', 'Pink')], default=None, max_length=100, verbose_name='Колір зображення 5')),
                ('image6', models.ImageField(blank=True, upload_to='', verbose_name='Зображення 6')),
                ('color6', models.CharField(blank=True, choices=[('#000000', 'Black'), ('#696969', 'Grey'), ('#0000FF', 'Blue'), ('#008000', 'Green'), ('#FF0000', 'Red'), ('#D2691E', 'Orange'), ('#DA70D6', 'Violet'), ('#87CEFA', 'Light Blue'), ('#FFFAFA', 'White'), ('#FFC0CB', 'Pink')], default=None, max_length=100, verbose_name='Колір зображення 6')),
                ('display', models.CharField(max_length=255, verbose_name='Діагональ, розширення, тип, інші особливості')),
                ('battery', models.CharField(max_length=255, verbose_name='Об`єм акумулятора')),
                ('memory', models.CharField(max_length=255, verbose_name='Об`єм оперативної та вбудованої пам`яті')),
                ('main_cam_mp', models.CharField(max_length=255, verbose_name='Основна камера')),
                ('frontal_cam_mp', models.CharField(max_length=255, verbose_name='Фронтальна камера')),
                ('soc', models.CharField(max_length=255, verbose_name='Процесор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.categories', verbose_name='Категорія')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
