# Generated by Django 4.0 on 2022-02-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.CharField(max_length=100, null=True, verbose_name='Колір продукту'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='related_models',
            field=models.CharField(blank=True, max_length=100000, verbose_name='Пов`язані моделі'),
        ),
    ]
